# Generated by Django 5.2.7 on 2025-10-31 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_khach_hang', models.CharField(max_length=10, unique=True)),
                ('ho_ten', models.CharField(max_length=200)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.CharField(max_length=200)),
                ('hang_thanh_vien', models.CharField(choices=[('Normal', 'Normal'), ('VIP', 'Vip'), ('Online', 'Online')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nguyen_lieu', models.CharField(max_length=10, unique=True)),
                ('ten_nguyen_lieu', models.CharField(max_length=50)),
                ('so_luong_ton_kho', models.FloatField()),
                ('chi_phi_nguyen_lieu', models.FloatField()),
                ('nha_cung_cap', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don_hang', models.CharField(max_length=10, unique=True)),
                ('thoi_gian_dat', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.FloatField()),
                ('trang_thai', models.CharField(choices=[('Đang xử lý', 'Pending'), ('Đã hoàn thành', 'Completed'), ('Đã hủy', 'Canceled')], max_length=20)),
                ('phuong_thuc_thanh_toan', models.CharField(choices=[('Tiền mặt', 'Cash'), ('Thẻ tín dụng', 'Credit')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mon', models.CharField(max_length=10, unique=True)),
                ('ten_mon', models.CharField(max_length=50)),
                ('loai_mon', models.CharField(choices=[('Burger', 'Burger'), ('Drink', 'Drink'), ('Combo', 'Combo'), ('Snack', 'Snack')], max_length=20)),
                ('gia_ban', models.FloatField()),
                ('don_vi_tinh', models.CharField(default='VND', max_length=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_thanh_toan', models.CharField(max_length=10, unique=True)),
                ('ngay_thanh_toan', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.FloatField()),
                ('phuong_thuc_thanh_toan', models.CharField(choices=[('Tiền mặt', 'Cash'), ('Thẻ tín dụng', 'Credit')], max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='MenuIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.FloatField()),
                ('don_vi_tinh', models.CharField(choices=[('Kilogram', 'Kilogram'), ('Item', 'Item')], max_length=20)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='core.menu')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.stockingredient')),
            ],
        ),
    ]
