# Generated by Django 5.2.7 on 2025-10-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_khach_hang', models.CharField(max_length=10, unique=True)),
                ('ho_ten', models.CharField(max_length=200)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.CharField(max_length=200)),
                ('hang_thanh_vien', models.CharField(choices=[('NRM', 'Normal'), ('VIP', 'VIP'), ('ONL', 'Online')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mon', models.CharField(max_length=10, unique=True)),
                ('ten_mon', models.CharField(max_length=50)),
                ('loai_mon', models.CharField(choices=[('BUR', 'Burger'), ('DRN', 'Drink'), ('CMB', 'Combo'), ('SNK', 'Snack')], max_length=3)),
                ('gia_ban', models.FloatField()),
                ('don_vi_tinh', models.CharField(default='VND', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nguyen_lieu', models.CharField(max_length=10, unique=True)),
                ('ten_nguyen_lieu', models.CharField(max_length=50)),
                ('so_luong_ton_kho', models.FloatField()),
                ('chi_phi_nguyen_lieu', models.FloatField()),
                ('nha_cung_cap', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.FloatField()),
                ('don_vi_tinh', models.CharField(choices=[('KG', 'Kilogram'), ('IT', 'Item')], max_length=2)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='core.menu')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.stockingredient')),
            ],
        ),
    ]
