# Generated by Django 5.2.7 on 2025-11-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tong_tien',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
