# Generated by Django 5.2.7 on 2025-11-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_tong_tien'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockingredient',
            name='used',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='core.order'),
        ),
    ]
